import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';

export const GENERATED_MARKER =
  '<!-- Generated by AgentFlow CLI. Run `npx @reforma/agentflow@latest update` to refresh. -->';
export const AGENTS_POINTER =
  'Larger than a quick fix: follow @AGENTFLOW.md.';

export const SETUP_COMPONENTS = ['skills', 'workflow', 'agents'] as const;
export type SetupComponent = (typeof SETUP_COMPONENTS)[number];

export const DOC_COMPONENTS = ['workflow', 'agents'] as const;
export type DocComponent = (typeof DOC_COMPONENTS)[number];

interface SetupConfig {
  version: 1;
  components: SetupComponent[];
}

export function generatedWorkflow(workflow: string): string {
  return `${GENERATED_MARKER}\n\n${workflow.trimEnd()}\n`;
}

export function isGeneratedWorkflow(path: string): boolean {
  return (
    existsSync(path) &&
    readFileSync(path, 'utf8').startsWith(GENERATED_MARKER)
  );
}

export function writeAtomically(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temporaryPath = `${path}.agentflow-tmp`;
  writeFileSync(temporaryPath, contents);
  renameSync(temporaryPath, path);
}

export function ensureAgentsPointer(cwd: string): void {
  const path = resolve(cwd, 'AGENTS.md');
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';

  if (current.includes('@AGENTFLOW.md')) {
    return;
  }

  if (current.length === 0) {
    writeAtomically(path, `${AGENTS_POINTER}\n`);
    return;
  }

  const withTrailingNewline = current.endsWith('\n') ? current : `${current}\n`;
  const withBlankLine = withTrailingNewline.endsWith('\n\n')
    ? withTrailingNewline
    : `${withTrailingNewline}\n`;

  writeAtomically(path, `${withBlankLine}${AGENTS_POINTER}\n`);
}

export function readSetupConfig(cwd: string): SetupConfig | null {
  const path = resolve(cwd, '.agentflow/config.json');

  if (!existsSync(path)) {
    return null;
  }

  const config = JSON.parse(readFileSync(path, 'utf8')) as Partial<SetupConfig>;

  if (
    config.version !== 1 ||
    !Array.isArray(config.components) ||
    config.components.some(
      (component) =>
        !SETUP_COMPONENTS.includes(component as SetupComponent),
    )
  ) {
    throw new Error('.agentflow/config.json is not a valid AgentFlow config.');
  }

  return config as SetupConfig;
}

export function writeSetupConfig(
  cwd: string,
  components: SetupComponent[],
): void {
  const config: SetupConfig = { version: 1, components };
  writeAtomically(
    resolve(cwd, '.agentflow/config.json'),
    `${JSON.stringify(config, null, 2)}\n`,
  );
}
