import {
  existsSync,
  readFileSync,
  renameSync,
  writeFileSync,
} from 'node:fs';
import { resolve } from 'node:path';

export const GENERATED_MARKER =
  '<!-- Generated by AgentFlow CLI. Run `npx @reforma/agentflow@latest update` to refresh. -->';
export const AGENTS_SNIPPET =
  '**Agent loop:** [AGENTFLOW.md](AGENTFLOW.md) — optional research → grill → usually `/plan` → sequential PRs (implement → `/code-review` → commit) → refresh context when needed.';

export function generatedWorkflow(workflow: string): string {
  return `${GENERATED_MARKER}\n\n${workflow.trimEnd()}\n`;
}

export function isGeneratedWorkflow(path: string): boolean {
  return (
    existsSync(path) &&
    readFileSync(path, 'utf8').startsWith(GENERATED_MARKER)
  );
}

export function writeAtomically(path: string, contents: string): void {
  const temporaryPath = `${path}.agentflow-tmp`;
  writeFileSync(temporaryPath, contents);
  renameSync(temporaryPath, path);
}

export function ensureIgnored(cwd: string): void {
  const path = resolve(cwd, '.gitignore');
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const alreadyIgnored = current
    .split(/\r?\n/)
    .some((line) => /^\/?\.agentflow\/?$/.test(line.trim()));

  if (alreadyIgnored) {
    return;
  }

  const separator = current.length === 0 || current.endsWith('\n') ? '' : '\n';
  writeAtomically(path, `${current}${separator}.agentflow/\n`);
}
